export { authApi }         from './auth.api'
export { educationApi }    from './education.api'
export { aiApi }           from './ai.api'
export { fitnessApi }      from './fitness.api'
export { dietaryApi }      from './dietary.api'
export { groomingApi }     from './grooming.api'
export { notificationsApi } from './notifications.api'
export { adminApi }        from './admin.api'
export { shoppingApi }     from './shopping.api'
export { groupsApi }       from './groups.api'
export { apiClient, authEventEmitter } from './client'
